version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development



# **************************************** Build and Running docker-compose.yml *******************************************
# docker-compose build
# docker-compose up